### ISSUE TITLE
Consider adding support for write RPCs

### ISSUE THREAD

**Issue by gbl08ma** [cinderblockgames/nano-public-api#7]
Consider adding support for RPCs that write to the network, like `process`, such that a proxied public node can be used with e.g. in-browser wallets like Nault or BananoVault.

**Comment by cinderblockgames** [comment]
I should have time to implement this after the weekend.

**Comment by cinderblockgames** [comment]
~~@gbl08ma Looks like this should not support `async` or `watch_work`.  What about `force`?~~

Yeah, won't support any of them.  Will just be the basic example as given in the [docs](https://docs.nano.org/commands/rpc-protocol/#process).

**Comment by cinderblockgames** [comment]
@gbl08ma This has been included in 1.2.0 for both nano and banano.
